export const REGISTER_WATCHER = 'REGISTER_WATCHER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LOGIN_WATCHER = 'LOGIN_WATCHER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const VERIFY_OTP_WATCHER = 'VERIFY_OTP_WATCHER'
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'

export const FORGOT_PASSWORD_WATCHER = 'FORGOT_PASSWORD_WATCHER'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'

export const RESET_PASSWORD_WATCHER = 'RESET_PASSWORD_WATCHER'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const ASYNC_BUYER_DATA_WATCHER = 'ASYNC_BUYER_DATA_WATCHER'
export const ASYNC_BUYER_DATA_SUCCESS = 'ASYNC_BUYER_DATA_SUCCESS'
export const ASYNC_BUYER_DATA_ERROR = 'ASYNC_BUYER_DATA_ERROR'